name: scrape
description: Helper package for analyzing the syntax of Dart programs.
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ^2.13.0

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  analyzer: any
  args: any
  path: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  lints: any
