include: package:lints/recommended.yaml

linter:
  rules:
    # In addition to lints/recommended:
    always_declare_return_types: true
    omit_local_variable_types: true
    prefer_single_quotes: true
    unawaited_futures: true

    # Remove from lints/recommended:
    constant_identifier_names: false
    non_constant_identifier_names: false
