name: dart2js_runtime_metrics
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
version: 0.2.0
description: >-
  `dart2js` can generate extra code to measure certain activities.
  This library provides access to the measurements at runtime.

environment:
  # Restrict the upper bound so that we can remove support for this in
  # a later version of the SDK without it being a breaking change.
  sdk: ">=2.14.0 <2.15.0"

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  expect: any
