include: package:lints/recommended.yaml

analyzer:
  errors:
    # There are currently 175 violations.
    always_declare_return_types: ignore
    # There are currently 60 violations.
    annotate_overrides: ignore
    # A number of class names mix UpperCamelCase with underscores.
    camel_case_types: ignore
    # This package freely and frequently imports implementation from analyzer.
    implementation_imports: ignore
    # Our test methods are named with snake_case.
    non_constant_identifier_names: ignore
    # There are currently 200 violations.
    omit_local_variable_types: ignore
    # There are currently 20 violations.
    unawaited_futures: ignore
    todo: ignore

  language:
    strict-casts: true

linter:
  rules:
    - await_only_futures
    - collection_methods_unrelated_type
    - dangling_library_doc_comments
    - depend_on_referenced_packages
    - empty_constructor_bodies
    - empty_statements
    - enable_null_safety
    - implicit_call_tearoffs
    - library_annotations
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_library_directive
    - unnecessary_parenthesis
    - unreachable_from_main
    - use_super_parameters
    - valid_regexps
